### PR TITLE
Added no-var-self rule

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
This is a common practice in JavaScript projects converted to TypeScript.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Not sure why the build is failing; it passes locally and I did run the `grunt-create-rule` command. Same with #132.

**Comment by HamletDRC** [comment]
Thanks, I will try to take a look later today! 

The no-function-expression and no-unnecessary-bind rules have a similar intent: use a lambda so you do not need to bind 'this'. 

I am interested to see what you do around nested lambdas where the inner lambda will need access to some self variable.

**Comment by JoshuaKGoldberg** [comment]
Renaming to something other than `self`.

In fact, I'll change this later today to require the user to name which names are banned.

**Comment by HamletDRC** [comment]
Should the rule just ban assigning 'this': 

    var x = this; // should be violation
    let self = this; // should be violation

I assume it should fail for any BinaryExpression where the operator is Equals and the right-hand-side is 'this'.

**Comment by HamletDRC** [comment]
you should also add test cases for using let and const as well, and not just var.

**Comment by JoshuaKGoldberg** [comment]
There are legitimate uses of assigning this. I'd rather not ban it altogether, though allowing "*"/-style wildcards for names can put that functionality in.

**Comment by HamletDRC** [comment]
I suggest you do this: 
* Look for BinaryExpressions assigning the 'this' reference in a variable/let/const statement
* Add an option to the rule for "variableName" that is a regex
* default the regex to '.*'
* compare the variable/let/const on the right hand side to your regex and create a violation if it does matches.

**Comment by HamletDRC** [comment]
This one is merged. Thanks @JoshuaKGoldberg

**Comment by JoshuaKGoldberg** [comment]
Oh sorry I was actually intending on implementing your suggestions! I'll take a look at what isn't in and send a PR soon. Thanks!

**Comment by JoshuaKGoldberg** [comment]
Looks perfect. :)

**Pull request closed without merging**
