### PR TITLE
Port TSX curly spacing rule.

### PR DESCRIPTION
**Pull request by lijunle**
- The ESLint version: https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-curly-spacing.js
- The rule options are the same: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md

### CODE REVIEW

**Comment by HamletDRC** [comment]
hi @lijunle
Thanks for the rule and taking the time to submit this.

One note: eslint-plugin-react is an MIT licensed project. So if we copy and paste a regular expression from that project to ours then we need to declare the project in our copyright notice and give proper credit. I would prefer to have zero dependencies, so I will rewrite this regular expression. 

Another note: the build is failing because the rule is not documented in readme.md and there is no metadata. 

Lastly, I will add some unit tests. 

Thanks for the submission! I will try to merge this today.

**Comment by HamletDRC** [comment]
Alright, I added tests and actually fixed an edge case. it all looks good. Thanks!

**Comment by lijunle** [comment]
Super thank you for handling this! You are awesome!

**Comment by HamletDRC** [comment]
Well, thanks for the PR! 

In the future, if you create a rule be sure to use: 

    grunt create-rule my-rule-name

Then it generates tests and documentation for you :)

**Pull request closed without merging**
