### PR TITLE
Support tslint 4 [WIP]

### PR DESCRIPTION
**Pull request by bondz**
Update the file path to match tslint > 4 file paths.

### CODE REVIEW

**Comment by bondz** [comment]
Tests depend on palantir/grunt-tslint#56 to update grunt-tslint to work with tslint >= 4

**Comment by bondz** [comment]
@msftclas done

**Comment by beckend** [comment]
[Function addExtraProps](https://github.com/4Catalyzer/found/blob/master/src/createConnectedRouter.js#L45) is never called in the entire codebase.

**Comment by HamletDRC** [comment]
If I accepted this PR then the newest version would require tslint 4.0.0 and would not be backwards compatible. I am researching how to make this backwards compatible.

**Comment by HamletDRC** [comment]
@bondz can you please sign that CLA? I think we need to make this change.

**Comment by jeffwilcox** [comment]
Hi, I'm going to have a machine account close and re-open this pull request. This sometimes is sufficient to bump the CLA subsystem to evaluate the CLA. Sorry for any inconvenience!

**Comment by bondz** [comment]
@HamletDRC a version bump with a peer dependency set for tslint >= 4 might be appropriate which is what I think was already in place. The readme would be updated to show the supported version of tslint and the new version. Thoughts?

**Comment by HamletDRC** [comment]
@bondz I released and closed 2.0.14 and now we are primed to merge this to master and release 3.0.0

I declared a peerdependency in 2.0.14 and it is changed in 3.0.0 to     "tslint": ">=4.0.0"

I'll take a look at this Linter not a function issue. I wonder if grunt-tslint is not compatible with tslint 4.0.0 either!

**Comment by HamletDRC** [comment]
@bondz we are blocked until grunt-tslint upgrades: https://github.com/palantir/grunt-tslint/issues/57

**Comment by HamletDRC** [comment]
@bondz I pushed everything to the branch 3_0_0. I also will remove the SyntaxKind class as part of this release.

**Comment by brndkfr** [comment]
@HamletDRC wonder if we should skip 3.0.0 and choose 4.0.0 instead to align with the tslint version.

**Comment by HamletDRC** [comment]
@brndkfr ok, 4.0.0 it is.

**Comment by HamletDRC** [comment]
When I run these rules against the codebase I see false positives in the no-unnecessary-semicolon rule. However, I cannot reproduce the failure in a unit test! 

I run tslint from command line: 

    $ npm install typescript -g && npm install tslint -g
    $ tslint -r ./dist/build/  -c ./tslint.json src/*.ts
    src/noForInRule.ts[31, 10]: Unnecessary semicolon
    src/preferConstRule.ts[30, 90]: Unnecessary semicolon

**Comment by bondz** [comment]
@HamletDRC 

> we are blocked until grunt-tslint upgrades: palantir/grunt-tslint#57

Yes. 

> When I run these rules against the codebase I see false positives

I also get errors like `Function name does not match /^[a-z][\w\d]+$/` on some other rules that pass the test.

**Comment by HamletDRC** [comment]
@bondz thank you for all the help! I am merging and starting the release process now.

**Comment by bondz** [comment]
Awesome. Happy to help :+1

**Pull request merged**
