### PR TITLE
Remove appveyor.yml

### LINKED ISSUE #613: Remove Appveyor
After #596 was merged - now Travis CI verifies on both Linux and Windows.

The question is: is there a need for two CI tools?

### PR DESCRIPTION
**Pull request by mesaugat**
Closes #613 

Might need to remove the integration and checks too.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Yup, we'll need to remove the integration first... which I don't have access to right now. Working on that and as soon as it's removed, this PR will go in 😊 thanks!

**Comment by JoshuaKGoldberg** [comment]
Merged in #636 that removes most of the contents of `appveyor.xml` pending getting the integration disabled. Still interested in this PR going in once that happens! 😊

**Comment by mesaugat** [comment]
Looks like I did something wrong while merging.

**Comment by mesaugat** [comment]
Here's a new pull request. 😞 #640

**Pull request closed without merging**
