### PR TITLE
apply prettier cleanup to latest changes

### PR DESCRIPTION
**Pull request by shiftkey**
#### PR checklist

-   [ ] Addresses an existing issue: fixes #0000
-   [ ] New feature, bugfix, or enhancement
    -   [ ] Includes tests
-   [x] Documentation update

#### Overview of change:

Prettier formatting for just about everything was added in #623:

https://github.com/Microsoft/tslint-microsoft-contrib/blob/f70d669310b3c225a1f1c3281bb493a1023caaab/package.json#L63

I was working on a contribution and wanted to ensure my changes fit this formatting, but running `npm run prettier` also formatted these files unrelated to my changes:

```
$ git rev-parse master
f70d669310b3c225a1f1c3281bb493a1023caaab
$ npm run prettier

> tslint-microsoft-contrib@6.0.0 prettier /Users/shiftkey/src/tslint-microsoft-contrib
> prettier --write "**/*.{js,ts,tsx,json,md}"

.github/ISSUE_TEMPLATE.md 380ms
...
tslint.json 17ms
$ git status   
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Release-Notes.md
	modified:   Releases.md
	modified:   TSLint-and-the-Microsoft-Security-Development-Lifecycle.md
	modified:   react-a11y-img-has-alt-Rule.md
	modified:   react-a11y-role-has-required-props-Rule.md
	modified:   react-a11y-role-supports-aria-props-Rule.md
	modified:   react-a11y-tabindex-no-positive-Rule.md
	modified:   react-ally-role-Rule.md
	modified:   react-no-dangerous-html-Rule.md

no changes added to commit (use "git add" and/or "git commit -a")
```

### CODE REVIEW

**Comment by shiftkey** [comment]
Feel free to clarify if some of these files (like `Releases.md` and `Release-Notes.md`) should not go through Prettier's formatting.

**Comment by IllusionMH** [comment]
@shiftkey these are Wiki files that were migrated to main repo.
There is PR #818 that moves them to `docs/` folder and Prettier formatter was applied in this [commit](https://github.com/Microsoft/tslint-microsoft-contrib/pull/818/commits/a35d7df0af26c42ba893bb320c87872b0c8894c2)

I will check if it will be possible to merge #818, so it won't produce a lot of unrelated changes for you.

**Comment by shiftkey** [comment]
@IllusionMH ok cool, looks like #818 is a superset of this change. I can workaround this in the meantime for my other work.

**Comment by IllusionMH** [comment]
@shiftkey for your PR you can format everything, rollback these files and use `git commit --no-verify` skip Pretties formatting on pre-commit hook.

**Comment by shiftkey** [comment]
@IllusionMH I think the husky hooks are smart enough to only lint staged changes before committing - I haven't had to `--no-verify` just yet 👍

**Comment by IllusionMH** [comment]
@shiftkey you are totally right - only staged files are affected!
I was under wrong impression after moving these files to another folder and avoiding formating.

**Pull request closed without merging**
