### PR TITLE
Add symbol to list of allowed typeof values

### PR DESCRIPTION
**Pull request by DickvdBrink**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

### CODE REVIEW

**Comment by HamletDRC** [comment]
Ah, I had no idea. Thanks!

**Comment by HamletDRC** [comment]
Thank you so much for taking the time to do this.

**Comment by DickvdBrink** [comment]
No problem, love the extra tslint-rules! :)

**Comment by HamletDRC** [comment]
Cool. On our side, we are trying to take every frequent code review comment and turn it into a rule. We have over 40 TypeScript devs on our project now, so the leads are getting a little buried!  I'm also trying to take the eslint rule list and reimplement them all so the TS community has parity with ES. 

If you have any rules in mind then I'd enjoy hearing them. I have dev time down to about 30 minutes a rule, so a lot can be implemented quickly.

**Pull request closed without merging**
